= Serverside Chat

[.notes]
--
Hi everyone! 

We're the ASF Infrastructure team, for those of you who don't know us

_do introductions_

Today we'd like to put some things straight:
* how we fit into the foundation at large
* how we support our larger community
* and how it is we do that

We're gonna start at the top and work our way down in scope from foundation
critical services and tools to user services and tools.
--
 
== ASF Infra
[%step]
* Infra is a Presidents committee, 
* There are 6 of us.
* we are all employees, not volunteers.

[.notes]
--
TODO
* What other context do we want to give our EUs

Infra is a President's committee responsible for the management and day-to-day
administration of the hardware and software vital to the smooth operation of the 
Foundation. Infra also reviews requests to install, deploy, or create new
systems and services for Foundation-wide consumption.

We don't directly report to the board, and don't have the same kinds of governance
that TLPs do. Generally speaking we're tasked with something and given the leeway to
implement as we see fit.

We are a small committee comprised of only 7.

FACT: Our Committer to IT staffer ratio is ~1300:1

--

== Foundation Services
[.notes]
--
To make sure we don't miss anything we're going to start at the top.
TODO fix this intro
--

=== Communications
[%step]
  * Mailing lists / Ponymail
  * Email Archives
  * Slack and GitHub Discussions

[.notes]
--
Mailing lists are the way that the foundation interacts with itself and is the only
official forum for discourse. It's important to ensure that we don't get spammed, 
that our mail isn't marked as spam, and that we've got good uptime

FACT: Email has 99.99% (4 9s) uptime over the last year.

Because the entire foundation is run via email, maintaining the mail archives for
providence is among the most important things we do. Ensuring that email maintains
its integrity through upgrades, migrations, and disasters is our responsibility.

FACT: Our archives currently hold $number-of-emails / dating back to $time-when

Infrastructure also supports real time communications via slack and GitHub discussions. 

Slack is a 3rd party tool given to infrastructure to steward for the whole foundation.

--

=== Core Infrastructure 
[%step]
  * LDAP (User Management)
  * DNS (Name Management)
  * PubSub (Event Management)
  * Puppet (Configuration Management)

[.notes]
--

User / Identity Management is important at a foundation where we tie logins together
and use them to sign code artifacts. Our public trust is built on the idea that we
verify contributors / code artifacts. In order for that trust to work properly we need
to be able to verify who is contributing.

FACT: there are over 9k registered committers at the ASF.

It's also important, from a security perspective, to ensure that our domain names are 
configured appropriately. We steward 100s of websites, documentation, services, CVEs,
build systems, tickets (both public and private) and emails. It's absolutely critical 
to ensure that we're not putting a bullseye on our back.

shoutout to the security team, without them the world would be that much less safe.

Additionally, PubSub servers to automate things and chain events together to create
meaningful, useful, processes

and finally we use Puppet internally to reduce the number of configurtaion variances
present across our systems

--

== Services for Projects
[.notes]
--
Not that we've gotten the important stuff out of the way, let's discuss the fun and
useful stuff. The bulk of our services are aimed at projects.

Being our primary service consumers much of our responsibility is enabling you, committers, 
to do that voodoo that you do so well.
--

=== Content distribution
[%step]
  * websites
  * blog posts
  * logo server
  * Atlassian Confluence

[.notes]
--
If Infra had a second biggest thing it does: it'd be content distribution.

fun facts: 
* sometime in 2011 the ASF had almost 300 active download mirrors in over 40 countries.
* a decade later in 2021 each hosted mirror synced 180GB of content available for download.
TODO: need a stat on how much content the CDN has served in teh last calendar year.


We support over $WEBSITES_NUM websites across 5 continents. Every project has one
and we here for that. We offer several different flavors of builder in house including
pelican and jenkins. 

We now leverage these builders to help your project build easy to use blogs hosted right on your
website

@wells -- a note about the logo server

a note about our wiki
--

=== Code Distribution 
[%step]
  * artifacts
  * distribution
  * archives
  * repository

[.notes]
--
--

=== Version Control Systems
[%step]
  * github / gitbox
  * svn

[.notes]
--
Infrastructure oversees the 2.5k repositories present in GitHub and mirrors them onto GitBox.
Subversion is also a thing we support.
--

=== Bug tracking
[%step]
  * Atlassian Jira
  * GitHub Issues
  * BugZilla

[.notes]
--
--

=== CI / CD systems
[%step]
  * Buildbot
  * Jenkins
  * 3rd party builders like GitHub Actions

[.notes]
--

--

=== Project VMs
[%step]
  * servers are available for projects upon request

[.notes]
--
--

    
== User Services and Tools

=== Self-Serve
[%step]
  * identity management
  * other self serve things

[.notes]
--
--

=== id.apache.org
[%step]
  * update LDAP Identity fields

[.notes]
--
--

== Upcoming projects
[%step]
  * ADP
  * keycloak

[.notes]
--
--

