= Serverside Chat

[.notes]
--
Hi everyone! 

we're the ASF Infrastructure team, for those of you who don't know us
* Introductions

Today we'd like to do a brief overview of what it is we do and offer exactly.

We're gonna start at the top and work our way down in scope from foundation
critical services and tools to user services and tools.

First some context around Infra:

Infra is a President's committee of the ASF responsible for management and day-to-day
administration of the hardware and software vital to the smooth operation 
of the Foundation. Infra also reviews requests to install, deploy, or create new
systems and services for Foundation-wide consumption.

--

== Foundation Services
[.notes]
--

--

=== Core Infrastructure 
[%step]
  * LDAP
  * DNS
  * PubSub

[.notes]
--
Identity management is important at a foundation where we tie logins together and use
them to sign code artifacts. Our public trust is built on the idea that we verify 
some things and sign our releases. In order for that web of trust to work properly
we need to be able to verify who is contributing.

It's also important, from a security perspective, to ensure that our domains are 
configured appropriately. We steward $PROJECTS_NUMBER worth of websites, documentation,
build systems, tickets (both public and private) and emails. It's absolutely critical 
to ensure that we're not putting a bullseye on our back.

shoutout to the security team, without them the world would be that much less safe.

--

=== Communications
[%step]
  * Mailing lists / Ponymail
  * Email Archives
  * Slack

[.notes]
--
Mailing lists are the way that the foundation interacts with itself and is the only
official forum for discourse. It's important to ensure that we don't get spammed, 
that our mail isn't marked as spam, and that we've got good uptime.

Because the entire foundation is run via email, maintaining the mail archives for
providence is among the most important things we do. Ensuring that email maintains
its integrity through upgrades, migrations, and disasters is our responsibility.

Infrastructure helps you in real time by providing slack. What used to be hipchat is
now a 3rd party donation given to infrastructure on behalf of the whole foundation.
--


== Services for Projects
[.notes]
--
The bulk of our services are aimed at projects. Being our primary service consumer
much of our responsibility is enabling you.
--

=== Content distribution
[%step]
  * websites
  * blog posts
  * logo server
  * Atlassian Confluence

[.notes]
--
We support over $WEBSITES_NUM websites across 5 continents. Every project has one
and we here for that. We offer several different flavors of builder in house including
pelican and jenkins. 

We now leverage these builders to help your project build easy to use blogs hosted right on your
website

@wells -- a note about the logo server

a note about our wiki
--

=== Code Distribution 
[%step]
  * artifacts
  * distribution
  * archives
  * repository

[.notes]
--
--

=== Version Control Systems
[%step]
  * github / gitbox
  * svn

[.notes]
--
--

=== Bug tracking
[%step]
  * Atlassian Jira
  * GitHub Issues
  * BugZilla

[.notes]
--
--

=== CI / CD systems
[%step]
  * Buildbot
  * Jenkins
  * 3rd party builders like GitHub Actions

[.notes]
--
--

=== Project VMs
[%step]
  * servers are available for projects upon request

[.notes]
--
--

    
== User Services and Tools

=== Self-Serve
[%step]
  * identity management
  * other self serve things

[.notes]
--
--

=== id.apache.org
[%step]
  * update LDAP Identity fields

[.notes]
--
--

== Upcoming projects
[%step]
  * ADP
  * keycloak

[.notes]
--
--

