name: "🐛 Found a Bug"
description: Report infra-apache website bugs (broken or incorrect behaviour).
labels: [ Bug ]
body:
  - type: markdown
    attributes:
      value: |
        - Please make sure to [search for existing issues](https://github.com/apache/infrastructure-website/issues) before filing a new one!
        - If the bug is related to **translation**, please report it in [Improve Translation](https://github.com/apache/infrastructure-website/issues/new?assignees=&labels=translation&template=improve-translation.yml).

  - type: dropdown
    attributes:
      label: Most appropriate sections of the infra-apache website?
      options:
        - About
        - Policies
        - Services and tools 
        - Documentation
        - Status
        - Contact Us
        - Other (specify if possible)
    validations:
      required: true

  - type: dropdown
    attributes:
      label: What is your operating system?
      options:
        - Windows
        - Mac OS
        - Linux
        - Android
        - iOS
        - Other (specify if possible)
    validations:
      required: false

  - type: input
    attributes:
      label: Web browser and version
      description: |
        In the address bar, on Chrome enter `chrome://version`, on Firefox enter `about:support`. On Safari, use `About Safari`.
    validations:
      required: false

  - type: textarea
    attributes:
      label: Actual Behavior
      placeholder: What is currently happening.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Expected Behavior
      description: |
        If you want to include screenshots, paste them into the markdown editor below.
      placeholder: What were you expecting?
    validations:
      required: true

  - type: textarea
    attributes:
      label: Steps to reproduce
      description: |
        - Add steps to reproduce bugs or add information on the place where the feature should be implemented.
        - Add links to a sample deployment or code.
    validations:
      required: true

  - type: input
    attributes:
      label: Would you like to work on the issue?
      description: |
        Please let us know if you can work on it or the issue should be assigned to someone else.
    validations:
      required: true