name: "🌐 Improve Translation"
description: Make a suggestion or report a problem about the translation of infra-apache website.
labels: [ Translation ]
body:
  - type: markdown
    attributes:
      value: |
        Please make sure to [search for existing issues](https://github.com/apache/infrastructure-website/issues) before filing a new one!

  - type: input
    attributes:
      label: Language
      description: |
        Which language page is the problem? Or translate into a new language?
    validations:
      required: true

  - type: textarea
    attributes:
      label: What improvement are you suggesting?
      description: |
        - Please give as much detail as possible to help us understand the change. 
        - What is the expected outcome?
    validations:
      required: true

  - type: input
    attributes:
      label: Would you like to work on the issue?
      description: |
        Please let us know if you can work on it or the issue should be assigned to someone else.
    validations:
      required: true