name: Build a Pelican Website
on:
  workflow_dispatch:
jobs:
  build-pelican:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@v4
        with:
          ref: 'master'
      - uses: apache/infrastructure-actions/pelican@93dfe4693bc118397840e7e4ae447e57a3eea7ee # main
        with:
          destination: 'asf-site'
          gfm: 'true'
